DROP TABLE IF EXISTS todos;

CREATE TABLE todos (
    id BIGSERIAL PRIMARY KEY,
    task_id BIGSERIAL REFERENCES tasks(id) ON DELETE CASCADE,
    inserted_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    content VARCHAR(128),
    todo_order int DEFAULT 1
);